<?php
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit();
}
$option_name_1  = 'facebook-url';
$option_name_2  = 'facebook-icon';
$option_name_3  = 'twitter-url';
$option_name_4  = 'twitter-icon';
$option_name_5  = 'linkedin-url';
$option_name_6  = 'linkedin-icon';
$option_name_7  = 'googleplus-url';
$option_name_8  = 'googleplus-icon';
$option_name_9  = 'youtube-url';
$option_name_10 = 'youtube-icon';
$option_name_11 = 'instagram-url';
$option_name_12 = 'instagram-icon';
$option_name_13 = 'pinterest-url';
$option_name_14 = 'pinterest-icon';
$option_name_15 = 'icon-size';
$option_name_16 = 'icon-color';
delete_option( $option_name_1 );
delete_option( $option_name_2 );
delete_option( $option_name_3 );
delete_option( $option_name_4 );
delete_option( $option_name_5 );
delete_option( $option_name_6 );
delete_option( $option_name_7 );
delete_option( $option_name_8 );
delete_option( $option_name_9 );
delete_option( $option_name_10 );
delete_option( $option_name_11 );
delete_option( $option_name_12 );
delete_option( $option_name_13 );
delete_option( $option_name_14 );
delete_option( $option_name_15 );
delete_option( $option_name_16 );
delete_site_option( $option_name_1 );
delete_site_option( $option_name_2 );
delete_site_option( $option_name_3 );
delete_site_option( $option_name_4 );
delete_site_option( $option_name_5 );
delete_site_option( $option_name_6 );
delete_site_option( $option_name_7 );
delete_site_option( $option_name_8 );
delete_site_option( $option_name_9 );
delete_site_option( $option_name_10 );
delete_site_option( $option_name_11 );
delete_site_option( $option_name_12 );
delete_site_option( $option_name_13 );
delete_site_option( $option_name_14 );
delete_site_option( $option_name_15 );
delete_site_option( $option_name_16 );
?>